export const BLOK_E = {
    kode: "E",
    judul: "Kondisi Perumahan dan Aset",
    pertanyaan: [
        {
            kode: "E1",
            variabel: "Status kepemilikan rumah yang ditempati",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Milik sendiri (bersertifikat)" },
                { kode: "2", label: "Milik sendiri (tidak bersertifikat)" },
                { kode: "3", label: "Kontrak/sewa" },
                { kode: "4", label: "Numpang/pinjam" },
                { kode: "5", label: "Rumah dinas" },
                { kode: "6", label: "Lainnya" },
            ],
        },
        {
            kode: "E2",
            variabel: "Jenis lantai terluas rumah",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Tanah" },
                { kode: "2", label: "Semen/plester" },
                { kode: "3", label: "Keramik/tegel" },
                { kode: "4", label: "Kayu/papan" },
                { kode: "5", label: "Lainnya" },
            ],
        },
        {
            kode: "E3",
            variabel: "Jenis dinding terluas rumah",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Bambu/kayu murahan" },
                { kode: "2", label: "Kayu kualitas baik" },
                { kode: "3", label: "Tembok (bata/batako)" },
                { kode: "4", label: "Seng/triplek" },
                { kode: "5", label: "Lainnya" },
            ],
        },
        {
            kode: "E4",
            variabel: "Jenis atap rumah",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Rumbia/ilalang" },
                { kode: "2", label: "Seng" },
                { kode: "3", label: "Genteng" },
                { kode: "4", label: "Asbes" },
                { kode: "5", label: "Lainnya" },
            ],
        },
        {
            kode: "E5",
            variabel: "Jumlah kamar tidur",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Tidak Ada Kamar" },
                { kode: "2", label: "1 kamar" },
                { kode: "3", label: "2 kamar" },
                { kode: "4", label: "3 kamar" },
                { kode: "5", label: ">= 4 kamar" },
            ],
        },
        {
            kode: "E6",
            variabel: "Sumber air minum utama",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Air ledeng/PDAM" },
                { kode: "2", label: "Sumur bor/pompa" },
                { kode: "3", label: "Sumur terlindungi" },
                { kode: "4", label: "Sumur tidak terlindungi" },
                { kode: "5", label: "Mata air" },
                { kode: "6", label: "Air hujan/sungai" },
                { kode: "7", label: "Air kemasan beli" },
            ],
        },
        {
            kode: "E7",
            variabel: "Fasilitas buang air besar (BAB)",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Jamban sendiri (tangki septik)" },
                { kode: "2", label: "Jamban bersama warga" },
                { kode: "3", label: "MCK umum" },
                { kode: "4", label: "Tidak ada / BAB sembarangan" },
            ],
        },
        {
            kode: "E8",
            variabel: "Sumber penerangan utama",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Listrik PLN (meteran sendiri)" },
                { kode: "2", label: "Listrik PLN (numpang tetangga)" },
                { kode: "3", label: "Listrik non-PLN/genset" },
                { kode: "4", label: "Tidak ada listrik" },
            ],
        },
        {
            kode: "E9",
            variabel: "Kepemilikan aset produktif dan kendaraan (centang yang dimiliki)",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Sepeda motor" },
                { kode: "2", label: "Mobil" },
                { kode: "3", label: "Sepeda" },
                { kode: "4", label: "Perahu/kapal" },
                { kode: "5", label: "Traktor/alat pertanian" },
                { kode: "6", label: "Lahan pertanian/kebun" },
                { kode: "7", label: "Ternak (sapi/kerbau/kambing)" },
                { kode: "8", label: "Tidak ada aset" },
            ],
        },
        {
            kode: "E10",
            variabel: "Kepemilikan aset elektronik/komunikasi (centang yang dimiliki)",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Telepon pintar (smartphone)" },
                { kode: "2", label: "TV" },
                { kode: "3", label: "Kulkas" },
                { kode: "4", label: "Komputer/laptop" },
                { kode: "5", label: "Tidak ada" },
            ],
        },
        {
            kode: "E11",
            variabel: "Apakah rumah pernah terdampak bencana (gempa, banjir, dll.) dalam 5 tahun terakhir?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak" },
            ],
        },
        {
            kode: "E11a",
            variabel: "Tahun bencana (jika E11 = 'Ya')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika E11 = 'Ya'",
        },
        {
            kode: "E11b",
            variabel: "Jenis bencana (jika E11 = 'Ya')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika E11 = 'Ya'",
        },
        {
            kode: "E12",
            variabel: "Apakah sudah mendapat bantuan perbaikan/rekonstruksi rumah pascabencana?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Pilih 'Tidak berlaku' kalau E11 = 'Tidak'",
            opsi: [
                { kode: "1", label: "Ya, sudah sepenuhnya" },
                { kode: "2", label: "Ya, sebagian" },
                { kode: "3", label: "Belum / tidak mendapat bantuan" },
                { kode: "4", label: "Tidak berlaku" },
            ],
        },
    ],
};