export const BLOK_L = {
    kode: "L",
    judul: "Catatan Enumerator",
    pertanyaan: [
        {
            kode: "L1",
            variabel: "Penilaian keseluruhan kondisi fisik bangunan",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Diisi enumerator berdasarkan pengamatan langsung",
            opsi: [
                { kode: "1", label: "Layak (struktur kokoh, atap/dinding/lantai dari bahan yang memenuhi syarat, tidak ada kerusakan berarti)" },
                { kode: "2", label: "Kurang layak (ada kerusakan pada salah satu komponen (atap/dinding/lantai) namun masih dapat ditempati)" },
                { kode: "3", label: "Tidak layak huni (kerusakan signifikan pada dua komponen atau lebih)" },
                { kode: "4", label: "Sangat tidak layak / rawan roboh" },
            ],
        },
        {
            kode: "L2",
            variabel: "Kondisi sanitasi dan kebersihan lingkungan",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Diisi enumerator berdasarkan pengamatan langsung",
            opsi: [
                { kode: "1", label: "Layak (kloset leher angsa dengan tangki septik/SPAL, lingkungan bersih)" },
                { kode: "2", label: "Cukup layak (ada kloset leher angsa namun tanpa tangki septik/SPAL memadai)" },
                { kode: "3", label: "Tidak layak (kloset bukan leher angsa, atau jamban cemplung, atau MCK umum tanpa pengolahan)" },
                { kode: "4", label: "Buruk (tidak ada jamban sama sekali / BAB sembarangan (BABS))" },
            ],
        },
        {
            kode: "L3",
            variabel: "Kondisi sosial lingkungan sekitar",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Diisi enumerator berdasarkan pengamatan langsung",
            opsi: [
                { kode: "1", label: "Kondusif (hubungan antar warga baik, tidak ada konflik)" },
                { kode: "2", label: "Cukup kondusif (interaksi terbatas, tidak ada konflik terbuka)" },
                { kode: "3", label: "Kurang kondusif (ada indikasi ketegangan atau isolasi sosial)" },
                { kode: "4", label: "Tidak kondusif (konflik aktif atau rawan kriminalitas)" },
            ],
        },
        {
            kode: "L4",
            variabel: "Kendala yang ditemui saat wawancara:",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "0", label: "Tidak ada kendala" },
                { kode: "1", label: "Wawancara diwakilkan anggota keluarga yang kurang mengetahui kondisi keluarga" },
                { kode: "2", label: "Responden tidak dapat berkomunikasi dengan baik (sakit keras, lansia berat, gangguan jiwa)" },
                { kode: "3", label: "Responden mengalami hambatan bahasa / tidak memahami bahasa Indonesia" },
                { kode: "4", label: "Responden menjawab tidak konsisten antara satu pertanyaan dengan pertanyaan lain" },
                { kode: "5", label: "Responden diduga memberikan jawaban tidak jujur / tidak sesuai kondisi nyata" },
                { kode: "6", label: "Responden ragu-ragu menjawab karena ada orang lain yang mendengar / mengawasi" },
                { kode: "7", label: "Responden hanya mau menjawab sebagian pertanyaan" },
                { kode: "8", label: "Waktu wawancara terganggu karena responden harus meninggalkan tempat" },
                { kode: "9", label: "Suasana tidak kondusif (banyak orang berkumpul di sekitar responden)" },
                { kode: "10", label: "Ada tekanan atau intervensi dari pihak ketiga (tokoh masyarakat, aparat desa, anggota keluarga lain) yang mempengaruhi jawaban" },
                { kode: "11", label: "Lainnya..." },
            ],
        },
        {
            kode: "L4a",
            variabel: "Sebutkan kendala lainnya/Catatan",
            jenis: "TEKS",
            wajib: false,
            aturan: "",
        },

        {
            kode: "L5",
            variabel: "Waktu mulai wawancara",
            jenis: "TEKS",
            wajib: true,
            aturan: "Format jam:menit, mis. '09:15'",
        },
        {
            kode: "L6",
            variabel: "Waktu selesai wawancara",
            jenis: "TEKS",
            wajib: true,
            aturan: "Format jam:menit, mis. '09:45'",
        },
        {
            kode: "L7",
            variabel: "Total durasi wawancara (menit)",
            jenis: "ANGKA",
            wajib: false,
            aturan: "Bisa dihitung otomatis dari L6-L5 di sisi app, atau diisi manual",
        },
    ],
};