export const BLOK_F = {
    kode: "F",
    judul: "Status dan Ketepatan Sasaran Bantuan Sosial",
    pertanyaan: [
        {
            kode: "F1",
            variabel: "Program Keluarga Harapan (PKH)",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Sedang menerima" },
                { kode: "2", label: "Pernah menerima, kini tidak" },
                { kode: "3", label: "Tidak pernah menerima" },
                { kode: "4", label: "Tidak tahu" },
            ],
        },
        {
            kode: "F1a",
            variabel: "Jumlah komponen PKH yang diterima",
            jenis: "ANGKA",
            wajib: false,
            aturan: "Diisi hanya jika F1 = 'Sedang menerima' atau 'Pernah menerima, kini tidak'",
        },
        {
            kode: "F2",
            variabel: "Bantuan Pangan Non-Tunai (BPNT/Sembako)",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Sedang menerima" },
                { kode: "2", label: "Pernah menerima, kini tidak" },
                { kode: "3", label: "Tidak pernah menerima" },
                { kode: "4", label: "Tidak tahu" },
            ],
        },
        {
            kode: "F3",
            variabel: "Bantuan Langsung Tunai (BLT) dari sumber manapun",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Sedang menerima" },
                { kode: "2", label: "Pernah menerima, kini tidak" },
                { kode: "3", label: "Tidak pernah menerima" },
            ],
        },
        {
            kode: "F3a",
            variabel: "Sumber BLT (jika F3 = 'Sedang menerima')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika F3 = 'Sedang menerima'",
        },
        {
            kode: "F4",
            variabel: "Program Indonesia Pintar (PIP/KIP)",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ada anak yang menerima" },
                { kode: "2", label: "Tidak ada / tidak menerima" },
                { kode: "3", label: "Tidak berlaku (tidak punya anak sekolah)" },
            ],
        },
        {
            kode: "F5",
            variabel: "Bantuan sosial lain dari pemerintah daerah",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak" },
            ],
        },
        {
            kode: "F5a",
            variabel: "Jenis bantuan lain (jika F5 = 'Ya')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika F5 = 'Ya'",
        },
        {
            kode: "F6",
            variabel: "Apakah Anda merasa layak menerima bantuan sosial yang saat ini diterima?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya, sangat layak" },
                { kode: "2", label: "Ya, layak" },
                { kode: "3", label: "Tidak yakin" },
                { kode: "4", label: "Merasa tidak layak lagi (kondisi sudah membaik)" },
            ],
        },
        {
            kode: "F7",
            variabel: "Apakah ada tetangga/orang lain yang lebih layak menerima bantuan namun belum terdaftar?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak" },
                { kode: "3", label: "Tidak tahu" },
            ],
        },
        {
            kode: "F8",
            variabel: "Apakah pernah mengalami kendala dalam penerimaan bantuan sosial?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Tidak ada kendala" },
                { kode: "2", label: "Bansos tidak tepat waktu" },
                { kode: "3", label: "Jumlah diterima kurang dari seharusnya" },
                { kode: "4", label: "Proses pengambilan sulit" },
                { kode: "5", label: "Data tidak sesuai (nama/NIK salah)" },
                { kode: "6", label: "Dikenakan potongan tidak resmi" },
                { kode: "7", label: "Bansos sudah lama tidak diterima" },
            ],
        },
    ],
};