export const BLOK_B = {
    kode: "B",
    judul: "Pendidikan Anggota Keluarga",
    pertanyaan: [
        {
            kode: "B1",
            variabel: "Pendidikan terakhir Kepala Keluarga",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Tidak pernah sekolah" },
                { kode: "2", label: "Tidak tamat SD" },
                { kode: "3", label: "Tamat SD/sederajat" },
                { kode: "4", label: "Tamat SMP/sederajat" },
                { kode: "5", label: "Tamat SMA/sederajat" },
                { kode: "6", label: "Diploma (D1-D3)" },
                { kode: "7", label: "Sarjana (S1)" },
                { kode: "8", label: "Pascasarjana (S2/S3)" },
            ],
        },
        {
            kode: "B2",
            variabel: "Pendidikan terakhir pasangan Kepala Keluarga (jika ada)",
            jenis: "PILIHAN_TUNGGAL",
            wajib: false,
            aturan: null,
            opsi: [
                { kode: "1", label: "Tidak pernah sekolah" },
                { kode: "2", label: "Tidak tamat SD" },
                { kode: "3", label: "Tamat SD/sederajat" },
                { kode: "4", label: "Tamat SMP/sederajat" },
                { kode: "5", label: "Tamat SMA/sederajat" },
                { kode: "6", label: "Diploma (D1-D3)" },
                { kode: "7", label: "Sarjana (S1)" },
                { kode: "8", label: "Magister/Doktor (S2/S3)" },
                { kode: "9", label: "Tidak berlaku (janda/duda/lajang)" },
            ],
        },
        {
            kode: "B3",
            variabel: "Apakah ada anak usia 7-18 tahun yang saat ini tidak bersekolah?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Tidak ada anak usia tersebut" },
                { kode: "2", label: "Ada, semua bersekolah" },
                { kode: "3", label: "Ada, sebagian tidak bersekolah" },
                { kode: "4", label: "Ada, semua tidak bersekolah" },
            ],
        },
        {
            kode: "B4",
            variabel: "Jika ada anak tidak bersekolah, apa alasan utamanya?",
            jenis: "MULTI_PILIHAN",
            wajib: false,
            aturan: "Pilih maksimal 2; hanya relevan jika B3 menunjukkan tidak bersekolah",
            opsi: [
                { kode: "1", label: "Biaya tidak mampu" },
                { kode: "2", label: "Sekolah terlalu jauh" },
                { kode: "3", label: "Bekerja membantu Keluarga" },
                { kode: "4", label: "Tidak ada minat/motivasi" },
                { kode: "5", label: "Sakit / disabilitas" },
                { kode: "6", label: "Sudah menikah" },
                { kode: "7", label: "Alasan lain" },
            ],
        },
        {
            kode: "B4a",
            variabel: "Alasan lain (jika B4 memilih 'Alasan lain')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika B4 mengandung 'Alasan lain'",
        },
        {
            kode: "B5",
            variabel:
                "Apakah ada anggota Keluarga yang menerima bantuan pendidikan (beasiswa/KIP) 1 tahun terakhir?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak" },
                { kode: "3", label: "Tidak tahu" },
            ],
        },
        {
            kode: "B5a",
            variabel: "Jenis bantuan pendidikan (jika B5 = Ya)",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika B5 = Ya",
        },
    ],
};