export const BLOK_A = {
    kode: "A",
    judul: "Identitas dan Kependudukan Keluarga",
    pertanyaan: [
        { kode: "A1", variabel: "Nama Kepala Keluarga", jenis: "TEKS", wajib: true, aturan: null },
        {
            kode: "A2",
            variabel: "Nomor Induk Kependudukan (NIK) Kepala Keluarga",
            jenis: "ANGKA",
            wajib: true,
            aturan: "16 digit sesuai KTP",
        },
        { kode: "A3", variabel: "Nomor Kartu Keluarga (KK)", jenis: "ANGKA", wajib: true, aturan: null },
        {
            kode: "A4",
            variabel: "Alamat lengkap (Jalan/RT/RW/Dusun)",
            jenis: "TEKS",
            wajib: true,
            aturan: null,
        },
        {
            kode: "A5",
            variabel: "Status kepesertaan dalam DTSEN",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Terdaftar dalam DTSEN" },
                { kode: "2", label: "Tidak terdaftar" },
                { kode: "3", label: "Tidak tahu" },
            ],
        },
        {
            kode: "A6",
            variabel: "Jenis kelamin Kepala Keluarga",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Laki-laki" },
                { kode: "2", label: "Perempuan" },
            ],
        },
        { kode: "A7", variabel: "Usia Kepala Keluarga (tahun)", jenis: "ANGKA", wajib: true, aturan: null },
        {
            kode: "A8",
            variabel: "Status perkawinan Kepala Keluarga",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Belum kawin" },
                { kode: "2", label: "Kawin" },
                { kode: "3", label: "Cerai hidup" },
                { kode: "4", label: "Cerai mati" },
            ],
        },
        {
            kode: "A9",
            variabel: "Jumlah anggota Keluarga (termasuk Kepala Keluarga)",
            jenis: "ANGKA",
            wajib: true,
            aturan: "Dalam satuan jiwa",
        },
        { kode: "A10a", variabel: "Balita (0-5 tahun), Laki-laki", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10b", variabel: "Balita (0-5 tahun), Perempuan", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10c", variabel: "Anak SD (6-12 tahun), Laki-laki", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10d", variabel: "Anak SD (6-12 tahun), Perempuan", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10e", variabel: "Remaja (13-17 tahun), Laki-laki", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10f", variabel: "Remaja (13-17 tahun), Perempuan", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10g", variabel: "Dewasa produktif (18-59 tahun), Laki-laki", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10h", variabel: "Dewasa produktif (18-59 tahun), Perempuan", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10i", variabel: "Lansia (60 tahun ke atas), Laki-laki", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        { kode: "A10j", variabel: "Lansia (60 tahun ke atas), Perempuan", jenis: "ANGKA", wajib: true, aturan: "Komposisi anggota Keluarga berdasarkan usia" },
        {
            kode: "A11",
            variabel: "Apakah ada anggota Keluarga dengan kondisi berikut? ",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Penyandang disabilitas" },
                { kode: "2", label: "Lanjut usia (>= 60 tahun)" },
                { kode: "3", label: "Ibu hamil/menyusui" },
                { kode: "4", label: "Anak tidak sekolah (usia 6-18 tahun)" },
                { kode: "5", label: "Tidak ada" },
            ],
        },
        {
            kode: "A11a",
            variabel: "Jenis disabilitas (jika ada penyandang disabilitas)",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika A11 mengandung 'Penyandang disabilitas'",
        },
        {
            kode: "A12",
            variabel: "Kepemilikan dokumen kependudukan (centang yang dimiliki)",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "KTP" },
                { kode: "2", label: "Kartu Keluarga" },
                { kode: "3", label: "Akta Kelahiran" },
                { kode: "4", label: "Akta Perkawinan" },
            ],
        },
    ],
};