export const BLOK_C = {
    kode: "C",
    judul: "Kesehatan Keluarga",
    pertanyaan: [
        {
            kode: "C1",
            variabel: "Apakah anggota Keluarga memiliki jaminan kesehatan?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Semua anggota memiliki Jaminan Kesehatan Gratis" },
                { kode: "2", label: "Jaminan Kesehatan Mandiri (bayar sendiri)" },
                { kode: "3", label: "Asuransi swasta" },
                { kode: "4", label: "Asuransi Perusahaan" },
                { kode: "5", label: "Tidak Memiliki Jaminan Kesehatan" },
            ],
        },
        {
            kode: "C2",
            variabel: "Jika tidak memiliki Jaminan Kesehatan, apa alasan utamanya?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Pilih 'Tidak berlaku' kalau C1 menunjukkan sudah punya jaminan kesehatan",
            opsi: [
                { kode: "1", label: "Tidak mampu bayar iuran" },
                { kode: "2", label: "Tidak tahu cara daftar" },
                { kode: "3", label: "Pernah punya, kini nonaktif" },
                { kode: "4", label: "Tidak merasa perlu" },
                { kode: "5", label: "Tidak berlaku (sudah punya)" },
            ],
        },
        {
            kode: "C3",
            variabel:
                "Apakah dalam 3 bulan terakhir ada anggota Keluarga yang sakit/memerlukan perawatan medis?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Jika 'Tidak', lanjut ke C6 (lewati C4 dan C5)",
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak" },
            ],
        },
        {
            kode: "C4",
            variabel: "Jika ya, ke mana biasanya berobat? (pilih yang paling sering)",
            jenis: "PILIHAN_TUNGGAL",
            wajib: false,
            aturan: "Hanya relevan jika C3 = 'Ya'",
            opsi: [
                { kode: "1", label: "Puskesmas" },
                { kode: "2", label: "Rumah Sakit" },
                { kode: "3", label: "Klinik/dokter swasta" },
                { kode: "4", label: "Bidan/perawat desa" },
                { kode: "5", label: "Dukun/pengobatan tradisional" },
                { kode: "6", label: "Tidak berobat / diobati sendiri" },
            ],
        },
        {
            kode: "C5",
            variabel: "Apa hambatan utama akses layanan kesehatan?",
            jenis: "MULTI_PILIHAN",
            wajib: false,
            aturan: "Pilih maksimal 2; hanya relevan jika C3 = 'Ya'",
            opsi: [
                { kode: "1", label: "Biaya" },
                { kode: "2", label: "Jarak jauh" },
                { kode: "3", label: "Tidak ada transportasi" },
                { kode: "4", label: "Pelayanan lambat" },
                { kode: "5", label: "Tidak punya BPJS" },
                { kode: "6", label: "Tidak ada hambatan" },
            ],
        },
        {
            kode: "C6",
            variabel: "Apakah ada anggota Keluarga yang menderita penyakit kronis/berat?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak" },
            ],
        },
        {
            kode: "C6a",
            variabel: "Sebutkan penyakit kronis/berat (jika C6 = 'Ya')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika C6 = 'Ya'",
        },
        {
            kode: "C7",
            variabel: "Status gizi balita (jika ada balita dalam Keluarga)",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Pilih 'Tidak ada balita dalam Keluarga' kalau tidak berlaku",
            opsi: [
                { kode: "1", label: "Gizi baik (normal)" },
                { kode: "2", label: "Gizi kurang (underweight)" },
                { kode: "3", label: "Gizi buruk (wasting)" },
                { kode: "4", label: "Stunting (pendek)" },
                { kode: "5", label: "Tidak ada balita dalam Keluarga" },
            ],
        },
    ],
};