const SEKTOR_PEKERJAAN = [
    { kode: "1", label: "Pertanian/perkebunan" },
    { kode: "2", label: "Perikanan/kelautan" },
    { kode: "3", label: "Peternakan" },
    { kode: "4", label: "Perdagangan/UMKM" },
    { kode: "5", label: "Jasa (ojek, buruh, dll.)" },
    { kode: "6", label: "Industri/manufaktur" },
    { kode: "7", label: "PNS/TNI/Polri" },
    { kode: "8", label: "Kehutanan" },
    { kode: "9", label: "Pertambangan/Penggalian" },
    { kode: "10", label: "Pengangkutan dan Pergudangan" },
    { kode: "11", label: "Aktivitas Keuangan dan Asuransi" },
    { kode: "12", label: "Aktivitas Kesehatan" },
    { kode: "13", label: "Lainnya" },
    { kode: "14", label: "Tidak bekerja" },
];

export const BLOK_D = {
    kode: "D",
    judul: "Ketenagakerjaan dan Pendapatan",
    pertanyaan: [
        {
            kode: "D1",
            variabel: "Status pekerjaan utama Kepala Keluarga saat ini",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Berusaha Sendiri" },
                { kode: "2", label: "Berusaha Dibantu Buruh Tidak Tetap/Pekerja Keluarga/Tidak Dibayar" },
                { kode: "3", label: "Berusaha Dibantu Buruh Tetap Dan Dibayar" },
                { kode: "4", label: "Buruh/Karyawan/Pegawai" },
                { kode: "5", label: "Pekerja Bebas" },
                { kode: "6", label: "Pekerja Keluarga" },
            ],
        },
        {
            kode: "D2",
            variabel: "Sektor pekerjaan utama Kepala Keluarga",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: SEKTOR_PEKERJAAN,
        },
        {
            kode: "D3",
            variabel: "Apakah pasangan Kepala Keluarga bekerja?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Jika 'Tidak', lewati D4, lanjut ke D5",
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak" },
            ],
        },
        {
            kode: "D4",
            variabel: "Sektor pekerjaan utama Pasangan",
            jenis: "PILIHAN_TUNGGAL",
            wajib: false,
            aturan: "Hanya relevan jika D3 = 'Ya'",
            opsi: SEKTOR_PEKERJAAN,
        },
        {
            kode: "D5",
            variabel:
                "Dalam 12 bulan terakhir, ketika penghasilan Keluarga tidak cukup, strategi apa yang pernah dilakukan?",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Meminjam uang (dari Keluarga, tetangga, atau rentenir)" },
                { kode: "2", label: "Meminjam dari lembaga keuangan / koperasi / bank" },
                { kode: "3", label: "Menjual barang/aset Keluarga (perabotan, perhiasan, dll.)" },
                { kode: "4", label: "Menjual aset produktif (ternak, lahan, peralatan usaha)" },
                { kode: "5", label: "Mengurangi frekuensi atau porsi makan" },
                { kode: "6", label: "Mengganti makanan dengan yang lebih murah / kurang bergizi" },
                { kode: "7", label: "Mencari pekerjaan tambahan / kerja serabutan" },
                { kode: "8", label: "Mengirim anggota Keluarga lain untuk bekerja" },
                { kode: "9", label: "Meminta bantuan dari Keluarga / saudara" },
                { kode: "10", label: "Meminta bantuan dari tetangga / komunitas" },
                { kode: "11", label: "Memanfaatkan bantuan sosial pemerintah" },
                { kode: "12", label: "Tidak melakukan strategi apapun / bertahan apa adanya" },
                { kode: "13", label: "Lainnya" },
            ],
        },
        {
            kode: "D6",
            variabel: "Dari seluruh strategi yang pernah dilakukan, mana yang paling sering digunakan?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: false,
            aturan:
                "Hanya relevan jika D5 diisi lebih dari 'Tidak melakukan strategi apapun'. Kode dinomori ulang 1-8 dari dokumen asli (yang mulai dari 5).",
            opsi: [
                { kode: "1", label: "Meminjam uang" },
                { kode: "2", label: "Menjual barang / aset Keluarga" },
                { kode: "3", label: "Menjual aset produktif" },
                { kode: "4", label: "Mengurangi / mengganti makan" },
                { kode: "5", label: "Mencari pekerjaan tambahan" },
                { kode: "6", label: "Meminta bantuan Keluarga / tetangga" },
                { kode: "7", label: "Memanfaatkan bantuan sosial pemerintah" },
                { kode: "8", label: "Lainnya" },
            ],
        },
        {
            kode: "D7",
            variabel:
                "Apakah pernah ada kebutuhan penting yang terpaksa tidak dipenuhi akibat kesulitan ekonomi?",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Biaya pendidikan anak (SPP, seragam, buku)" },
                { kode: "2", label: "Biaya pengobatan / kesehatan" },
                { kode: "3", label: "Kebutuhan pangan / gizi" },
                { kode: "4", label: "Tagihan listrik / air" },
                { kode: "5", label: "Kebutuhan pakaian" },
                { kode: "6", label: "Tidak pernah ada kebutuhan yang tidak terpenuhi" },
                { kode: "7", label: "Lainnya" },
            ],
        },
        {
            kode: "D8",
            variabel:
                "Apakah ada anggota Keluarga yang memiliki keterampilan/keahlian tertentu (meskipun belum dijadikan usaha)?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Jika 'Tidak ada', lewati D9 & D10, lanjut ke D11",
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak ada" },
            ],
        },
        {
            kode: "D9",
            variabel: "Keterampilan atau keahlian apa yang dimiliki?",
            jenis: "MULTI_PILIHAN",
            wajib: false,
            aturan: "Hanya relevan jika D8 = 'Ya'",
            opsi: [
                { kode: "1", label: "Memasak / kuliner / pengolahan makanan" },
                { kode: "2", label: "Menjahit / bordir / kerajinan tekstil" },
                { kode: "3", label: "Pertukangan / bangunan" },
                { kode: "4", label: "Pertanian / perkebunan / peternakan" },
                { kode: "5", label: "Perikanan / budidaya laut" },
                { kode: "6", label: "Kecantikan / tata rias" },
                { kode: "7", label: "Otomotif / bengkel" },
                { kode: "8", label: "Perdagangan / jual beli" },
                { kode: "9", label: "Teknologi / komputer / media sosial" },
                { kode: "10", label: "Lainnya" },
            ],
        },
        {
            kode: "D10",
            variabel: "Apa kendala utama sehingga keterampilan tersebut belum berkembang menjadi usaha?",
            jenis: "MULTI_PILIHAN",
            wajib: false,
            aturan: "Hanya relevan jika D8 = 'Ya'",
            opsi: [
                { kode: "1", label: "Tidak memiliki modal awal" },
                { kode: "2", label: "Tidak memiliki peralatan / alat produksi" },
                { kode: "3", label: "Tidak ada akses ke pasar / pembeli" },
                { kode: "4", label: "Belum mendapat pendampingan / pelatihan lanjutan" },
                { kode: "5", label: "Tidak ada waktu (sibuk mengurus rumah / anak)" },
                { kode: "6", label: "Tidak ada dukungan dari Keluarga" },
                { kode: "7", label: "Tidak tahu cara memulai usaha" },
                { kode: "8", label: "Kondisi kesehatan tidak memungkinkan" },
                { kode: "9", label: "Lainnya" },
            ],
        },
        {
            kode: "D11",
            variabel:
                "Apakah ada sumber daya/peluang di lingkungan sekitar yang bisa dimanfaatkan untuk meningkatkan penghasilan Keluarga?",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Lahan kosong yang bisa dimanfaatkan" },
                { kode: "2", label: "Kelompok usaha / koperasi di sekitar tempat tinggal" },
                { kode: "3", label: "Program pelatihan dari pemerintah atau lembaga lain" },
                { kode: "4", label: "Pasar / pembeli potensial di sekitar tempat tinggal" },
                { kode: "5", label: "Jaringan Keluarga / kenalan yang bisa membantu usaha" },
                { kode: "6", label: "Tidak ada peluang yang teridentifikasi" },
                { kode: "7", label: "Lainnya" },
            ],
        },
        {
            kode: "D12",
            variabel: "Berapa total pendapatan Keluarga dari semua sumber per bulan? (estimasi)",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Catat estimasi, bukan data pasti",
            opsi: [
                { kode: "1", label: "< Rp 1.000.000" },
                { kode: "2", label: "Rp 1.000.001 - Rp 2.000.000" },
                { kode: "3", label: "Rp 2.000.001 - Rp 3.500.000" },
                { kode: "4", label: "Rp 3.500.001 - Rp 5.000.000" },
                { kode: "5", label: "Rp 5.000.001 - Rp 10.000.000" },
                { kode: "6", label: "> Rp 10.000.000" },
            ],
        },
        {
            kode: "D13",
            variabel: "Sumber pendapatan Keluarga",
            jenis: "MULTI_PILIHAN",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Gaji/upah tetap" },
                { kode: "2", label: "Usaha/dagang" },
                { kode: "3", label: "Pertanian/kebun" },
                { kode: "4", label: "Perikanan/ternak" },
                { kode: "5", label: "Kiriman Keluarga" },
                { kode: "6", label: "Bantuan sosial pemerintah" },
                { kode: "7", label: "Pinjaman" },
                { kode: "8", label: "Lainnya" },
            ],
        },
        {
            kode: "D14",
            variabel: "Apakah pendapatan saat ini cukup memenuhi kebutuhan pokok sehari-hari?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Sangat cukup" },
                { kode: "2", label: "Cukup" },
                { kode: "3", label: "Kurang" },
                { kode: "4", label: "Sangat kurang / sering tidak makan" },
            ],
        },
        {
            kode: "D15",
            variabel: "Bagaimana kondisi ekonomi Keluarga dibanding 1 tahun lalu?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Jauh lebih baik" },
                { kode: "2", label: "Sedikit lebih baik" },
                { kode: "3", label: "Sama saja" },
                { kode: "4", label: "Sedikit lebih buruk" },
                { kode: "5", label: "Jauh lebih buruk" },
            ],
        },
        {
            kode: "D16",
            variabel: "Apakah ada anggota Keluarga yang memiliki usaha/UMKM?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak" },
            ],
        },
        {
            kode: "D16a",
            variabel: "Jenis usaha (jika D16 = 'Ya')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika D16 = 'Ya'",
        },
        {
            kode: "D16b",
            variabel: "Omzet usaha per bulan, dalam Rupiah (jika D16 = 'Ya')",
            jenis: "ANGKA",
            wajib: false,
            aturan: "Diisi hanya jika D16 = 'Ya'",
        },

        // D17 -- pengeluaran per bulan (dipecah dari tabel jadi 7 sub-pertanyaan)
        { kode: "D17a", variabel: "Pengeluaran per bulan -- Pangan/makanan (Rp)", jenis: "ANGKA", wajib: false, aturan: "Bagian dari D17" },
        { kode: "D17b", variabel: "Pengeluaran per bulan -- Pendidikan anak (Rp)", jenis: "ANGKA", wajib: false, aturan: "Bagian dari D17" },
        { kode: "D17c", variabel: "Pengeluaran per bulan -- Kesehatan (Rp)", jenis: "ANGKA", wajib: false, aturan: "Bagian dari D17" },
        { kode: "D17d", variabel: "Pengeluaran per bulan -- Listrik/air/bahan bakar (Rp)", jenis: "ANGKA", wajib: false, aturan: "Bagian dari D17" },
        { kode: "D17e", variabel: "Pengeluaran per bulan -- Transportasi (Rp)", jenis: "ANGKA", wajib: false, aturan: "Bagian dari D17" },
        { kode: "D17f", variabel: "Pengeluaran per bulan -- Cicilan/hutang (Rp)", jenis: "ANGKA", wajib: false, aturan: "Bagian dari D17" },
        { kode: "D17g", variabel: "Pengeluaran per bulan -- Lainnya (Rp)", jenis: "ANGKA", wajib: false, aturan: "Bagian dari D17" },
    ],
};