export const BLOK_G = {
    kode: "G",
    judul: "Perkembangan Ekonomi Keluarga (Desil Kesejahteraan)",
    pertanyaan: [
        {
            kode: "G1",
            variabel: "Bagaimana kondisi pemenuhan kebutuhan pangan Keluarga saat ini?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Selalu terpenuhi dengan baik" },
                { kode: "2", label: "Cukup terpenuhi" },
                { kode: "3", label: "Kadang kekurangan" },
                { kode: "4", label: "Sering kekurangan / tidak mampu makan 3x sehari" },
            ],
        },
        {
            kode: "G2",
            variabel: "Berapa hari dalam seminggu Keluarga bisa makan dengan lauk bergizi (daging/ikan/telur)?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Setiap hari (7 hari)" },
                { kode: "2", label: "4-6 hari seminggu" },
                { kode: "3", label: "1-3 hari seminggu" },
                { kode: "4", label: "Hampir tidak pernah" },
            ],
        },
        {
            kode: "G3",
            variabel: "Apakah Keluarga menabung dalam 6 bulan terakhir?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya, rutin menabung" },
                { kode: "2", label: "Kadang-kadang" },
                { kode: "3", label: "Tidak, penghasilan habis untuk kebutuhan harian" },
                { kode: "4", label: "Tidak, bahkan harus berhutang" },
            ],
        },
        {
            kode: "G4",
            variabel: "Berapa total hutang/pinjaman aktif yang dimiliki saat ini?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Tidak ada hutang" },
                { kode: "2", label: "< Rp 1.000.000" },
                { kode: "3", label: "Rp 1.000.001 - Rp 5.000.000" },
                { kode: "4", label: "Rp 5.000.001 - Rp 20.000.000" },
                { kode: "5", label: "> Rp 20.000.000" },
            ],
        },
        {
            kode: "G5",
            variabel: "Apakah dalam 2 tahun terakhir ada perubahan signifikan pada kondisi ekonomi Keluarga?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Meningkat signifikan (naik desil / graduasi dari kemiskinan)" },
                { kode: "2", label: "Sedikit meningkat" },
                { kode: "3", label: "Tidak berubah" },
                { kode: "4", label: "Sedikit menurun" },
                { kode: "5", label: "Menurun signifikan (jatuh miskin / kondisi memburuk drastis)" },
            ],
        },
        {
            kode: "G6",
            variabel: "Faktor apa yang paling berpengaruh terhadap perubahan kondisi ekonomi tersebut?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: "Pilih 'Tidak ada perubahan signifikan' kalau G5 = 'Tidak berubah'",
            opsi: [
                { kode: "1", label: "Perubahan pekerjaan/pendapatan" },
                { kode: "2", label: "Bencana/musibah" },
                { kode: "3", label: "Sakit anggota Keluarga" },
                { kode: "4", label: "Dampak program pemerintah" },
                { kode: "5", label: "Perubahan harga bahan pokok" },
                { kode: "6", label: "Penambahan/pengurangan anggota RT" },
                { kode: "7", label: "Tidak ada perubahan signifikan" },
            ],
        },
        {
            kode: "G7",
            variabel: "Apakah Keluarga memiliki akses ke layanan keuangan formal?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Rekening tabungan bank" },
                { kode: "2", label: "Pinjaman bank/KUR" },
                { kode: "3", label: "Koperasi" },
                { kode: "4", label: "Pinjaman online (legal)" },
                { kode: "5", label: "Tidak ada akses keuangan formal" },
            ],
        },
    ],
};