export const BLOK_L = {
    kode: "L",
    judul: "Catatan Enumerator",
    pertanyaan: [
        {
            kode: "L1",
            variabel: "Kondisi fisik rumah (hasil observasi langsung)",
            jenis: "TEKS",
            wajib: true,
            aturan: null,
        },
        {
            kode: "L2",
            variabel: "Sanitasi/kebersihan lingkungan (hasil observasi langsung)",
            jenis: "TEKS",
            wajib: true,
            aturan: null,
        },
        {
            kode: "L3",
            variabel: "Kondisi sosial sekitar (hasil observasi langsung)",
            jenis: "TEKS",
            wajib: true,
            aturan: null,
        },
        {
            kode: "L4",
            variabel: "Hal lain yang perlu dicatat",
            jenis: "TEKS",
            wajib: false,
            aturan: null,
        },
        {
            kode: "L5",
            variabel: "Penilaian Enumerator terhadap Kondisi Ekonomi Responden",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Sangat miskin / memprihatinkan" },
                { kode: "2", label: "Miskin" },
                { kode: "3", label: "Hampir miskin / rentan" },
                { kode: "4", label: "Tidak miskin" },
            ],
        },
        {
            kode: "L6",
            variabel: "Kendala yang ditemui saat wawancara",
            jenis: "TEKS",
            wajib: false,
            aturan: null,
        },
        {
            kode: "L7",
            variabel: "Waktu mulai wawancara",
            jenis: "TEKS",
            wajib: true,
            aturan: "Format jam:menit, mis. '09:15'",
        },
        {
            kode: "L8",
            variabel: "Waktu selesai wawancara",
            jenis: "TEKS",
            wajib: true,
            aturan: "Format jam:menit, mis. '09:45'",
        },
        {
            kode: "L9",
            variabel: "Total durasi wawancara (menit)",
            jenis: "ANGKA",
            wajib: false,
            aturan: "Bisa dihitung otomatis dari L7-L8 di sisi app, atau diisi manual",
        },
    ],
};