const SKALA_AKSES_FASILITAS = [
    { kode: "1", label: "Sangat Mudah" },
    { kode: "2", label: "Mudah" },
    { kode: "3", label: "Sulit" },
    { kode: "4", label: "Sangat Sulit" },
];

function aksesFasilitas(kode, namaFasilitas) {
    return {
        kode,
        variabel: `${namaFasilitas}`,
        jenis: "PILIHAN_TUNGGAL",
        wajib: true,
        aturan: null,
        opsi: SKALA_AKSES_FASILITAS,
    };
}

export const BLOK_I = {
    kode: "I",
    judul: "Kebutuhan Prioritas dan Akses Layanan Dasar",
    pertanyaan: [
        { kode: "I1a", variabel: "Pendapatan/pekerjaan yang layak", jenis: "ANGKA", wajib: false, aturan: "Pilih maksimal 3, urutkan 1=paling mendesak." },
        { kode: "I1b", variabel: "Akses layanan kesehatan", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1c", variabel: "Biaya pendidikan anak", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1d", variabel: "Perbaikan/kepemilikan rumah", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1e", variabel: "Air bersih", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1f", variabel: "Listrik", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1g", variabel: "Jalan/transportasi", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1h", variabel: "Modal usaha", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1i", variabel: "Bantuan sosial (pangan/tunai)", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1j", variabel: "Pelatihan keterampilan kerja", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1k", variabel: "Perlindungan hukum/sosial", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1l", variabel: "Lainnya", jenis: "ANGKA", wajib: false, aturan: "Bagian dari I1" },
        { kode: "I1m", variabel: "Sebutkan kebutuhan 'Lainnya' (jika I1l diisi)", jenis: "TEKS", wajib: false, aturan: "Diisi hanya jika I1l diisi" },

        aksesFasilitas("I2a", "Puskesmas/klinik terdekat"),
        aksesFasilitas("I2b", "Sekolah SD terdekat"),
        aksesFasilitas("I2c", "Sekolah SMP terdekat"),
        aksesFasilitas("I2d", "Pasar/warung sembako"),
        aksesFasilitas("I2e", "Kantor pemerintah (desa/kec.)"),
        aksesFasilitas("I2f", "Jalan aspal/beraspal"),
        aksesFasilitas("I2g", "Sinyal internet/telepon"),

        {
            kode: "I3",
            variabel: "Apakah Keluarga pernah mengikuti program pelatihan keterampilan/vokasional dari pemerintah?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya" },
                { kode: "2", label: "Tidak (lanjut I4)" },
            ],
        },
        {
            kode: "I3a",
            variabel: "Jenis pelatihan keterampilan/vokasional yang pernah diikuti (pilih satu atau lebih)",
            jenis: "MULTI_PILIHAN",
            wajib: false,
            aturan: "Diisi hanya jika I3 = 'Ya'. Boleh pilih lebih dari satu.",
            opsi: [
                { kode: "1", label: "Menjahit/Tata Busana" },
                { kode: "2", label: "Tata Boga/Kuliner" },
                { kode: "3", label: "Tata Rias" },
                { kode: "4", label: "Komputer/Teknologi Informasi" },
                { kode: "5", label: "Bahasa Asing (misalnya Bahasa Mandarin, Jepang, Korea, Inggris)" },
                { kode: "6", label: "Pertanian" },
                { kode: "7", label: "Perikanan" },
                { kode: "8", label: "Peternakan" },
                { kode: "9", label: "Otomotif" },
                { kode: "10", label: "Las/Konstruksi" },
                { kode: "11", label: "Kewirausahaan/UMKM" },
                { kode: "12", label: "Digital Marketing/E-commerce" },
                { kode: "13", label: "Lainnya" },
            ],
        },
        {
            kode: "I3a1",
            variabel: "Sebutkan jenis pelatihan 'Lainnya' (jika I3a memilih 'Lainnya')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika I3a memilih opsi 'Lainnya' (13)",
        },
        {
            kode: "I3b",
            variabel: "Pelaksana pelatihan (pilih satu atau lebih)",
            jenis: "MULTI_PILIHAN",
            wajib: false,
            aturan: "Diisi hanya jika I3 = 'Ya'. Boleh pilih lebih dari satu.",
            opsi: [
                { kode: "1", label: "Pemerintah Desa/Kelurahan" },
                { kode: "2", label: "Pemerintah Kabupaten/Kota" },
                { kode: "3", label: "Pemerintah Provinsi" },
                { kode: "4", label: "Kementerian Ketenagakerjaan" },
                { kode: "5", label: "Balai Latihan Kerja (BLK)" },
                { kode: "6", label: "Dinas Sosial" },
                { kode: "7", label: "Dinas Ketenagakerjaan" },
                { kode: "8", label: "Dinas Pendidikan" },
                { kode: "9", label: "Kementerian/Lembaga lainnya" },
                { kode: "10", label: "Program kerja sama pemerintah daerah dengan pihak luar negeri (misalnya program Bahasa Mandarin)" },
                { kode: "11", label: "Lainnya" },
            ],
        },
        {
            kode: "I3b1",
            variabel: "Sebutkan pelaksana pelatihan 'Lainnya' (jika I3b memilih 'Lainnya')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika I3b memilih opsi 'Lainnya' (11)",
        },
        {
            kode: "I4",
            variabel:
                "Apakah Keluarga berminat mengikuti program pemberdayaan ekonomi (usaha/keterampilan) jika difasilitasi pemerintah?",
            jenis: "PILIHAN_TUNGGAL",
            wajib: true,
            aturan: null,
            opsi: [
                { kode: "1", label: "Ya, sangat berminat" },
                { kode: "2", label: "Berminat" },
                { kode: "3", label: "Tidak berminat" },
                { kode: "4", label: "Tidak tahu" },
            ],
        },
        {
            kode: "I4a",
            variabel: "Jenis kegiatan yang diminati (jika I4 = 'Ya, sangat berminat' atau 'Berminat')",
            jenis: "TEKS",
            wajib: false,
            aturan: "Diisi hanya jika I4 menunjukkan berminat",
        },
    ],
};